filter:
    excluded_paths: [tests/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 3